"""ASS caption generation: one word per event, cut on, cut off.

ASS rather than drawtext for two reasons. It gives real control over the box
behind a highlighted word, and CapCut imports it, so the same file that burns
into the render also drops straight into a manual edit.

Everything here works in *output* time. Word timings arrive in source time and
are mapped through the Timeline first; a word that fell inside a trimmed
silence still appears, snapped to the nearest surviving frame.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from .config import Style
from .timeline import Timeline
from .transcript import Transcript, Word

WORD_STYLE = "Word"
HIGHLIGHT_STYLE = "Highlight"


def format_time(seconds: float) -> str:
    """ASS timestamps are H:MM:SS.cc - centiseconds, and one hour digit."""
    seconds = max(0.0, seconds)
    total_cs = int(round(seconds * 100))
    hours, remainder = divmod(total_cs, 360000)
    minutes, remainder = divmod(remainder, 6000)
    secs, centis = divmod(remainder, 100)
    return f"{hours:d}:{minutes:02d}:{secs:02d}.{centis:02d}"


def escape_text(text: str) -> str:
    """ASS treats braces as override blocks and backslashes as escapes."""
    return (
        text.replace("\\", "\\\\")
        .replace("{", "\\{")
        .replace("}", "\\}")
        .replace("\n", " ")
        .strip()
    )


@dataclass
class CaptionEvent:
    start: float
    end: float
    text: str
    style: str = WORD_STYLE


def build_header(style: Style) -> str:
    caption = style.caption
    render = style.render
    border_style = 1  # outline + shadow
    return "\n".join([
        "[Script Info]",
        "; Generated by reelkit. Times are on the cut timeline, not the raw file.",
        "ScriptType: v4.00+",
        f"PlayResX: {render.width}",
        f"PlayResY: {render.height}",
        "WrapStyle: 2",
        "ScaledBorderAndShadow: yes",
        "YCbCr Matrix: TV.709",
        "",
        "[V4+ Styles]",
        "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, "
        "OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, "
        "ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, "
        "Alignment, MarginL, MarginR, MarginV, Encoding",
        # The plain word: brand text colour, no outline, a hard offset shadow.
        _style_line(
            WORD_STYLE, caption.font, caption.size,
            primary=style.ass_text, outline=style.ass_outline,
            back=style.ass_shadow, bold=caption.bold,
            border_style=border_style, outline_w=caption.outline,
            shadow=caption.shadow, margin_l=caption.margin_h,
            margin_r=caption.margin_h, margin_v=caption.margin_v,
        ),
        # The highlighted word: BorderStyle 3 turns the outline colour into an
        # opaque box, which is how the brand block behind the type is made.
        _style_line(
            HIGHLIGHT_STYLE, caption.font, caption.size,
            primary=style.ass_highlight_text, outline=style.ass_highlight_block,
            back=style.ass_highlight_block, bold=True,
            border_style=3, outline_w=max(6.0, caption.outline),
            shadow=0.0, margin_l=caption.margin_h,
            margin_r=caption.margin_h, margin_v=caption.margin_v,
        ),
        "",
        "[Events]",
        "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, "
        "Effect, Text",
    ])


def _style_line(
    name: str, font: str, size: int, *, primary: str, outline: str, back: str,
    bold: bool, border_style: int, outline_w: float, shadow: float,
    margin_l: int, margin_r: int, margin_v: int,
) -> str:
    fields = [
        name, font, str(size), primary, primary, outline, back,
        "-1" if bold else "0", "0", "0", "0",
        "100", "100", "0", "0",
        str(border_style), f"{outline_w:g}", f"{shadow:g}",
        "2", str(margin_l), str(margin_r), str(margin_v), "1",
    ]
    return "Style: " + ",".join(fields)


def build_events(
    transcript: Transcript,
    timeline: Timeline,
    *,
    style: Style,
    window: tuple[float, float] | None = None,
    highlight: list[Word] | None = None,
    min_duration: float = 0.12,
    max_duration: float = 1.2,
    hold_gap: float = 0.4,
) -> list[CaptionEvent]:
    """One event per word, in output time, with the highlights styled."""
    highlight_keys = {
        (round(w.start, 3), w.clean) for w in (highlight or [])
    }
    # A hair of tolerance: a word starting exactly on the boundary must not
    # be lost to float rounding.
    start_bound, end_bound = window or (0.0, float("inf"))
    start_bound -= 1e-3

    events: list[CaptionEvent] = []
    for word in transcript.words:
        if not (start_bound <= word.start < end_bound):
            continue
        text = escape_text(word.text)
        if not text:
            continue
        out_start = timeline.map_time_clamped(word.start)
        out_end = timeline.map_time_clamped(word.end)

        duration = out_end - out_start
        if duration < min_duration:
            out_end = out_start + min_duration
        elif duration > max_duration:
            out_end = out_start + max_duration
        if out_start >= timeline.duration:
            continue
        out_end = min(out_end, timeline.duration)

        is_highlight = (round(word.start, 3), word.clean) in highlight_keys
        events.append(CaptionEvent(
            start=out_start,
            end=out_end,
            text=text.upper() if style.caption.uppercase else text,
            style=HIGHLIGHT_STYLE if is_highlight else WORD_STYLE,
        ))

    events.sort(key=lambda e: e.start)
    # Cut on, cut off. Two rules, and the second one matters more than it
    # looks: no two words ever share the screen, and consecutive words butt
    # straight up against each other. Leaving the natural gap between words
    # blanks the caption for a frame or two on every word, which reads as a
    # flicker. A real pause - longer than `hold_gap` - is still left empty,
    # because that is a beat, not a stutter.
    for current, following in zip(events, events[1:]):
        if current.end > following.start:
            current.end = following.start
        elif following.start - current.end <= hold_gap:
            current.end = following.start
    return [e for e in events if e.end > e.start]


def render_ass(
    transcript: Transcript,
    timeline: Timeline,
    *,
    style: Style,
    window: tuple[float, float] | None = None,
    highlight: list[Word] | None = None,
    hold_gap: float = 0.4,
) -> str:
    events = build_events(
        transcript, timeline, style=style, window=window,
        highlight=highlight, hold_gap=hold_gap,
    )
    lines = [build_header(style)]
    for event in events:
        lines.append(
            f"Dialogue: 0,{format_time(event.start)},{format_time(event.end)},"
            f"{event.style},,0,0,0,,{event.text}"
        )
    return "\n".join(lines) + "\n"


def write_ass(path: str | Path, content: str) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return path
